### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by garulovilla** [ytakanashi/Tascher#1]
Translation

It is a wonderful application with many possibilities, thanks for all the work.
Unfortunately, I have found it difficult to understand all the great options. Would it be possible to have the version translated to English?

**Comment by ytakanashi** [comment]
@garulovilla 
I'm considering the translated version.
However, due to my English skills, I am not sure when it will be release.

**Comment by garulovilla** [comment]
Very cool 😎. I look forward to that version and fully understand the situation, English is not my native language either. I hope someone from the community could help with that translation. Anyway, thank you very much for the work done.
