### ISSUE TITLE
Please support windows 11.

### ISSUE THREAD

**Issue by bommbo** [ytakanashi/Tascher#3]
Same as title. It's so slow for winodows 11.

**Comment by hahv** [comment]
Great software, but as @bommbo said. When press Ctrl + Shift + Z to open the switcher, It took long time for Win 11 (probably 3-4 secs). Hope this can be fixed! Thanks the author.

**Comment by ytakanashi** [comment]
@bommbo
@hahv

Thank you for posting issues.
The reason for the slow speed is due to the absence of the Interface key under HKLM.
So I've added "**IIDGuid**" options and it seems to work fine still on Windows11 22H2(OS Build 22621.2715).

https://frostmoon.sakura.ne.jp/Tascher/debug.html

Something like this(Tascher.cfg):
```
[IIDGuid]
IApplicationView={372E1D3B-38D3-42E4-A15B-8AB2B178F513}
IApplicationViewCollection={1841C6D7-4F9D-42C0-AF41-8747538F10E5}
IVirtualDesktopManager={A5CD92FF-29BE-454C-8D04-D82879FB3F1B}
```

**Comment by bommbo** [comment]
Yes, probably 3-4 secs, It's not working  still when I add  "IIDGuid" options.

**Comment by hahv** [comment]
> @bommbo @hahv
> 
> Thank you for posting issues. The reason for the slow speed is due to the absence of the Interface key under HKLM. So I've added "**IIDGuid**" options and it seems to work fine still on Windows11 22H2(OS Build 22621.2715).
> 
> [frostmoon.sakura.ne.jp/Tascher/debug.html](https://frostmoon.sakura.ne.jp/Tascher/debug.html)
> 
> Something like this(Tascher.cfg):
> 
> ```
> [IIDGuid]
> IApplicationView={372E1D3B-38D3-42E4-A15B-8AB2B178F513}
> IApplicationViewCollection={1841C6D7-4F9D-42C0-AF41-8747538F10E5}
> IVirtualDesktopManager={A5CD92FF-29BE-454C-8D04-D82879FB3F1B}
> ```
As @bommbo reported,  adding "IIDGuid" options did not work!
I tested on Win 11 Pro - Version 10.0.22621 Build 22621.
I wonder how to get the values `IApplicationView`, etc. Does these values fixed or depend on each computer?

**Comment by ytakanashi** [comment]
@bommbo
@hahv

What message do you see when you try to show the list window ?

https://frostmoon.sakura.ne.jp/Tascher/debug2.html

The IID can be different depending on the build version of Windows 11.

**Comment by bommbo** [comment]
I tested debug2 version. It's shown all result = 1. 

![image](https://github.com/ytakanashi/Tascher/assets/61496351/1c3223ee-8c05-49be-a32d-6e2a7735a807)

**Comment by ytakanashi** [comment]
Thank you for confirming. 
In the debug.html version, Would it works fine if you set **[ListView]EnumWindows=1** ?

**Comment by bommbo** [comment]
Yes.bro, I will close this issue. please add a link to debug version and configuration file in readme file.

**Comment by ytakanashi** [comment]
@bommbo 

Added link to README.md. This is the same URL as in the post above.
"Tascher.cfg" is created when quit Tascher and Then try [ListView]EnumWindows=1, etc.
